[package]
name = "rust-sample"
version = "0.1.0"
edition = "2021"
description = "Sample AI implementation in Rust for the car game"

[lib]
crate-type = ["cdylib"]

[dependencies]

[profile.release]
opt-level = 3
lto = true
debug = false
